// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutIQ.Data;

#nullable disable

namespace ScoutIQ.Migrations
{
    [DbContext(typeof(ScoutIQDbContext))]
    [Migration("20260626145329_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoutIQ.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<double>("age_potential_gap")
                        .HasColumnType("float");

                    b.Property<double>("defending")
                        .HasColumnType("float");

                    b.Property<double>("dribbling")
                        .HasColumnType("float");

                    b.Property<decimal>("market_value_eur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("overall")
                        .HasColumnType("float");

                    b.Property<double>("pace")
                        .HasColumnType("float");

                    b.Property<double>("passing")
                        .HasColumnType("float");

                    b.Property<double>("physic")
                        .HasColumnType("float");

                    b.Property<int>("position_group_ATT")
                        .HasColumnType("int");

                    b.Property<int>("position_group_GK")
                        .HasColumnType("int");

                    b.Property<int>("position_group_MID")
                        .HasColumnType("int");

                    b.Property<double>("potential")
                        .HasColumnType("float");

                    b.Property<double>("shooting")
                        .HasColumnType("float");

                    b.Property<string>("short_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("value_per_rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
