// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScoutIQ.Data;

#nullable disable

namespace ScoutIQ.Migrations
{
    [DbContext(typeof(ScoutIQDbContext))]
    [Migration("20260710215534_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScoutIQ.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Predicted_Market_Value_EUR")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<double>("assists_per_90")
                        .HasColumnType("float");

                    b.Property<double>("assists_per_game")
                        .HasColumnType("float");

                    b.Property<double>("avg_minutes")
                        .HasColumnType("float");

                    b.Property<double>("avg_transfer_fee")
                        .HasColumnType("float");

                    b.Property<string>("club")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("contract_years_left")
                        .HasColumnType("float");

                    b.Property<string>("country_of_birth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("country_of_citizenship")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("discipline_score")
                        .HasColumnType("float");

                    b.Property<double>("experience_score")
                        .HasColumnType("float");

                    b.Property<string>("foot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("foot_enc")
                        .HasColumnType("int");

                    b.Property<double>("gc_per_90")
                        .HasColumnType("float");

                    b.Property<double>("goal_contributions")
                        .HasColumnType("float");

                    b.Property<double>("goals_per_90")
                        .HasColumnType("float");

                    b.Property<double>("goals_per_game")
                        .HasColumnType("float");

                    b.Property<double>("height_in_cm")
                        .HasColumnType("float");

                    b.Property<decimal>("highest_market_value_in_eur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("international_caps")
                        .HasColumnType("float");

                    b.Property<double>("international_goals")
                        .HasColumnType("float");

                    b.Property<double>("intl_ratio")
                        .HasColumnType("float");

                    b.Property<int>("is_international")
                        .HasColumnType("int");

                    b.Property<double>("log_market_value")
                        .HasColumnType("float");

                    b.Property<decimal>("market_value_in_eur")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("max_transfer_fee")
                        .HasColumnType("float");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("num_transfers")
                        .HasColumnType("float");

                    b.Property<int>("player_id")
                        .HasColumnType("int");

                    b.Property<string>("position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("position_enc")
                        .HasColumnType("int");

                    b.Property<string>("sub_position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("total_assists")
                        .HasColumnType("float");

                    b.Property<double>("total_games")
                        .HasColumnType("float");

                    b.Property<double>("total_goals")
                        .HasColumnType("float");

                    b.Property<double>("total_minutes")
                        .HasColumnType("float");

                    b.Property<double>("total_red")
                        .HasColumnType("float");

                    b.Property<double>("total_transfer_fee")
                        .HasColumnType("float");

                    b.Property<double>("total_yellow")
                        .HasColumnType("float");

                    b.Property<double>("value_growth")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
